---
development:
  adapter: mysql2
  database: app_dev
  host: db
  username: app_dev
  password: app_dev_password
  encoding: utf8mb4
test:
  adapter: mysql2
  database: app_test
  host: db
  username: app_test
  password: app_test_password
  encoding: utf8mb4
production:
  adapter: mysql2
  database: app_prod
  host: db
  username: app_dev
  password: app_prod_password
  encoding: utf8mb4
