version: "3"
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # Update 'VARIANT' to pick a version of Ruby: 3, 3.1, 3.0, 2, 2.7, 2.6
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: "2.7-bullseye"
        NODE_VERSION: "lts/*"
    volumes:
      - ..:/workspace:cached
    environment:
      TZ: Asia/Tokyo
      REDMINE_LANG: ja
    command: sleep infinity
    network_mode: service:db
    depends_on:
      - db
  db:
    image: mariadb:10.5
    restart: unless-stopped
    volumes:
      - ./mariadb/customize.cnf:/etc/mysql/mariadb.conf.d/customize.cnf
      - ./mariadb/create-db-user.sql:/docker-entrypoint-initdb.d/create-db-user.sql
      - mariadb-data:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: mariadb
  # db:
  #   image: postgres:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ./postgres/create-db-user.sql:/docker-entrypoint-initdb.d/create-db-user.sql
  #     - postgres-data:/var/lib/postgresql/data
  #   environment:
  #     TZ: Asia/Tokyo
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: postgres
  #     POSTGRES_PASSWORD: postgres
volumes:
  mariadb-data: null
#   postgres-data: null
